version: '2.13.0'
services: 
  backend:
    build: ./backend
    container_name: api_c
    ports:
      - '4040:4040'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    container_name: web_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  
  

